### ISSUE TITLE
Constraints incomplete after upload to TER

### ISSUE THREAD

**Issue by cocowerbung** [DanielHaring/TYPO3-Crystalis#4]
Inside Git repository, all constraints appear as they should – no matter which branch you'll checkout. 

However, the uploaded version located at TYPO3 Extension Repository (TER) lacks the _suggests_ array. Therefore, if using _realurl_ and/or _static_info_tables_ it's a game of pure chance if the extensions are loaded in the correct order.

Referring to the [official API documentation](http://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/DeclarationFile/Index.html) everything is configured the right way. There may be some issues with the extension uploader or the TER itself.

This has to be investigated somehow.

**Comment by HARING** [comment]
This issue is caused by [Typo3ExtensionUtils] (https://github.com/etobi/Typo3ExtensionUtils) during upload process. The *suggests* array simply is ignored.

I'll rely on an alternative way of uploading to TER for future releases.
